# Generated by Django 3.2.3 on 2021-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travianAPI', '0003_materiales_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('size', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Materiales',
            new_name='Materials',
        ),
    ]
