# Generated by Django 3.2.3 on 2021-05-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travianAPI', '0005_auto_20210516_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='troops',
            old_name='size',
            new_name='troops_size',
        ),
    ]
